#+title: Teoria dei modelli
#+author: Silvia Barbina
#+date: Scuola Estiva di Logica 2025

#+begin_latex
\clearpage
#+end_latex

* Preliminari

Si lavora con un linguaggio
\begin{equation*}
\mathcal{L} = \set{\set{R_{i}}_{i \in I}, \set{f_{j}}_{j \in J}, \set{c_{k}}_{k \in K}}
\end{equation*}

Definizioni di base:
a. Una _teoria_ è un insieme di \(\mathcal{L}\)-enunciati:
b. Una \(\mathcal{L}\)-struttura \(M\) è un modello della teoria \(T\) se per ogni \(\sigma \in T\), \(M\vDash \sigma\). Si scrive \(M\vDash T\).

   \(T\) è _coerente_, o _consistente_, se ammette un modello.
c. Con \(\operatorname{Mod}(T)\) si indica la classe di tutti i modelli tella teoria \(T\).
d. Con \(\operatorname{Th}(M)\) si indica la teoria della struttura \(M\), ossia
   \begin{equation*}
	\operatorname{Th}(M) \coloneqq\set{\sigma: M\vDash\sigma,\sigma\text{ enunciato}}.
   \end{equation*}
e. Se \(T\) è una teoria e \(\sigma\) è un enunciato,
   \begin{equation*}
	T\vDash\sigma\text{ per ogni }M\vDash T
   \end{equation*}
f. \(T\) è una teoria _completa_ se per ogni enunciato \(\sigma\) si ha
   \begin{equation*}
	T\vDash \sigma\quad\text{o}\quadT\vDash\lnot\sigma.
   \end{equation*}
g. Scriviamo \(M\equiv N\), e diremo che \(M,N\) sono _elementarmente equivalenti_ se
   \begin{equation*}
	\operatorname{Th}(M)=\operatorname{Th}(N)
   \end{equation*}

Alcune domande naturali:
1. Data \(T\), possiamo descrivere \(\operatorname{Mod}(T)\)? In generale, la domanda ha senso quando \(T\) è completa
2. Data \(M\) (struttura), \(\operatorname{Th}(M)\) è sempre completa. Come sono fatti i modelli di \(\operatorname{Th}(M)\)?
3. Come stabilire se una data teoria \(T\) è completa?
4. Data una struttura \(M\), è possibile descrivere \(\operatorname{Th}(M)\) in modo efficace? (per esempio mediante degli assiomi)

#+BEGIN_esempio
Sia \(T\) una teoria \(\omega\)-categorica, ossia avente un unico modello infinito numerabile a meno di isomorfismo. Allora
- \(T\) è completa;
- i modelli infinito numerabili di \(T\) sono tutti isomorfi;
- una classificazione di \(\operatorname{Mod}(T)\) si ha banalmente per \(T\) totalmente categorica.
#+END_esempio

_Abusi di notazioni_.
- Una struttura verrà denotata dal suo dominio \(M\); non distinguiamo tra simboli nel linguaggio e le loro interpretazioni in \(M\).
- Se \(A \subseteq M\), definiamo un'espansione di \(\mathcal{L}\):
  \begin{equation*}
	\mathcal{L}(A) = L\cup\set{a \mid a \in A}.
  \end{equation*}
  Una \(\mathcal{L}(A)\)-formula ha parametri in \(A\).
- Scriviamo "\(\varphi \in \mathcal{L}\)" per "\(\varphi\) è una \(\mathcal{L}\)-formula".
- Tuple di variabili/costanti si denotano con \(x\)/\(a\), e, occasionalmente \(\bar{x}\)/\(\bar{a}\). \(|x|\) denota la lunghezza della tupla \(x\) (ex: \(a \in M^{|a|}\))
- \(M,N,U,V\) denotano struttura e \(A,B,C\) sono sottoinsiemi del dominio di una struttura.
** Immersioni e immersioni elementari

Se \(M,N\) sono due \(\mathcal{L}\)-struttura, allora
1. \(f:M\to N\) è una _immersione_ se e solo se per ogni \(\varphi(x) \in \mathcal{L}\) _atomica_ (oppure senza quantificatori) e \(\forall a \in M^{|x|}\)
   \begin{equation*}
		M\vDash\varphi(a)\quad\iff\quad N\vDash \varphi\big(f(a)\big)
   \end{equation*}
   Troviamo una copia isomorfa di \(M\) dentro \(N\).
2. \(f:M\to N\) è una _immersione elementare_ se per ogni \(\varphi(x) \in \mathcal{L}\) e \(\forall a \in M^{|x|}\)
   \begin{equation*}
		M\vDash\varphi(a)\quad\iff\quad N\vDash \varphi\big(f(a)\big)
   \end{equation*}

Inoltre
1. \(M\) è _sottostruttura_ di \(N\) (\(M \subseteq N\)) se l'inclusione \(i:M\to N\) è una immersione.
2. \(M\) è _sottostruttura elementare_ di \(N\) (\(M \preceq N\)) se l'inclusione \(i:M\to N\) è una immersione elementare.
3. Una immersione biiettiva è un isomorfismo ed è, in particolare, un'immersione elementare.
4. Ogni immersione è iniettiva
   \begin{equation*}
		M\vDash a=b\quad\iff\quad N\vDash f(a)=f(b)
   \end{equation*}

#+begin_esempio
Sia \(\mathcal{L}_{lo}=\set{<}\), con \(<\) simbolo di relazione binaria. Allora \((\R,<)\) è una \(\mathcal{L}_{lo}\)-struttura, dove \(<\) è (interpretato come) l'ordine usuale sui reali.

Gli intervalli \([0,1]\) e \([0,2] \subseteq \R\) sono \(\mathcal{L}_{lo}\) strutture e sono entrambi sottostrutture di \(\R\). Inoltre \([0,1]\cong [0,2]\), con \(x\mapsto 2x\) [[id:fff05de6-4e25-4c73-b0a6-ce5358000801][isomorfismo]].

_Ma_ l'inclusione \([0,1]\subseteq[0,2]\) non è elementare. Infatti, sia
\begin{equation*}
\varphi(x):\quad \forall y \ (y<x \lor y=x)
\end{equation*}
allora \([0,1]\vDash\varphi(1)\) ma \([0,1]\not\vDash\varphi(1)\).

Altre osservazioni: \([0,1]\not\preceq \R\) e \([0,1]\not\equiv \R\). Però \([0,1]\equiv[0,2]\) poiché \([0,1]\cong[0,2]\).
#+end_esempio

#+BEGIN_thm
([[id:37e670b4-8d9e-47f8-8c9d-e32d51009635][Criterio di Tarski-Vaught]]) Per ogni [[id:fdc86b04-828f-4f24-8cdf-948211d93a95][sottoinsieme]] \(A \subseteq N\), sono fatti equivalenti:
1. \(A\) è il dominio di una sottostruttura elementare \(M\preceq N\);
2. per ogni [[id:f9a821a8-6c1d-4f71-b75f-62a71e394446][formula]] \(\varphi(x) \in \mathcal{L}(A)\) con \(|x|=1\)
   \begin{equation*}
		N\vDash \exists\,x\ \varphi(x)\quad \implies\quad N\vDash \varphi(b)\text{ per qualche } b \in A
   \end{equation*}
#+END_thm

#+BEGIN_definizione
Sia \(\lambda\) un ordinale. Allora una _catena di \(\mathcal{L}\)-strutture_ è una successione \(\langle M_{i}\mid i <\lambda\rangle\) tale che, per ogni \(i<j<\lambda\), \(M_{i} \subseteq M_{j}\).
#+END_definizione

L'_unione della catena_ è la struttura \(M\) dove
- il dominio è \(\bigcup_{i<\lambda} M_{i}\);
- \(c\) costante, allora \(c^{M} =c^{M_{i}}\) per qualche \(i<\lambda\);
- \(f\) funzione, \(\bar{a} \in M^{n}\), allora \(f^{M}(\bar{a}) = f^{M_{i}}(\bar{a})\) per \(i\) tale che \(\bar{a} \in M_{i}^{n}\);
- \(R\) relazione, allora \(R^{M} = \bigcup_{i<\lambda} R^{M_{i}}\).

** Teorema di Lowenheim-Skolem all'ingiù

#+BEGIN_thm
Sia \(N\) una \(\mathcal{L}\)-struttura con \(|N|\ge |\mathcal{L}|+\omega\), e sia \(A \subseteq N\).

Allora per ogni \(\lambda\) tale che \(|A|+|\mathcal{L}|\le \lambda \le |N|\) esiste \(M\preceq N\) tale che
a. \(A \subseteq M\)
b. \(|M|=\lambda\).
#+END_thm

* Due Teorie

** Teoria degli ordini lineari

Sia \(\mathcal{L}_{lo}=\set{<}\), con \(<\) relazione binaria. Una \(\mathcal{L}_{lo}\) struttura è un _ordine lineare_ se soddisfa
1. \(\forall x\ \lnot(x<x)\);
2. \(\forall x,y,z\ \big[(x<y \land y<z)\implies x<z\big]\);
3. \(\forall x,y\ [x<y \lor y<x \lor x=y]\).
Un ordine lineare è _denso_ se soddisfa
4. \(\exists x,y\ [x<y]\)
5. \(\forall x,y\ \big[(x<y)\implies \exists z\ (x<z \land z<y)\big]\).
Un ordine lineare è _senza estremi_ se
6. \(\forall x\)

??? (vedi [[id:c9007816-7ef7-41aa-bc68-38526c8aec31][Ordine lineare]], [[id:59d9fb18-ff76-4e78-a088-4d6b462b58e3][Ordine denso]], [[id:a6c2fea9-a043-40b0-a307-6c050b1d4eee][Ordine senza punto finale]])

(\(T_{lo}\) e \(T_{dlo}\))

** Teoria dei grafi

Sia \(\mathcal{L}_{gph} = \set{R}\). Un _grafo_ è una \(\mathcal{L}_{gph}\)-struttura che soddisfa

??? (Vedi [[id:84458b05-0b76-4967-8276-baf222382c78][Teoria dei grafi]], [[id:e05d8a6f-634d-4a62-8b1d-23eefeaab240][Teoria dei grafi aleatori]])

(\(T_{gph}\) e \(T_{rg}\))

I modelli di \(T_{dlo}\) e \(T_{rg}\) sono necessariamente infiniti.

** Risultati per \(T_{dlo}\) e \(T_{rg}\)

#+BEGIN_definizione
Siano \(M,N\) due \(\mathcal{L}\)-strutture. Un'_immersione parziale_ è una mappa iniettiva
\begin{equation*}
p:\operatorname{dom}(p) \subseteq M\to N
\end{equation*}
tale che
1. per ogni relazione \(n\)-aria \(R\), \(a \in \operatorname{dom}(p)^{n}\)
   \begin{equation*}
	a \in R^{M}\quad\iff\quad p(a) \in R^{N}
   \end{equation*}
2. per ogni funzione \(n\)-aria \(f\), \(a, f^{M}(a) \in \operatorname{dom}(p)^{n}\)
   \begin{equation*}
	p\big(f^{M}(a)\big)=f^{N}\big(p(a)\big)
   \end{equation*}
3. per ogni costante \(c\) tale che \(c^{M} \in \operatorname{dom}(p)\)
   \begin{equation*}
	p(c^{M})=c^{N}
   \end{equation*}
#+END_definizione

#+BEGIN_definizione
\(M,N\) sono _parzialmente isomorfe_ se esiste una collezione \(I\neq\emptyset\) di immersioni parziali tali che
1. se \(p \in I\) e \(a \in M\), esiste \(\hat{p} \in I\) con \(p \subseteq \hat{p}\) e \(a \in \operatorname{dom}(\hat{p})\);
2. se \(p \in I\) e \(b \in M\), esiste \(\hat{p} \in I\) con \(p \subseteq \hat{p}\) e \(b \in \operatorname{rng}(\hat{p})\).
#+END_definizione

#+BEGIN_lem
(Andirivieni, o back-and-forth) Se \(\card{M}=\card{N}=\omega\) e \(M,N\) sono parzialmente isomorfe via \(I\), allora \(M\cong N\).
#+END_lem
#+BEGIN_proof
Enumeriano \(M,N\), dicendo
\begin{align*}
M&=\langle a_{i}: i <\omega\rangle\\
N&=\langle b_{i}: i <\omega\rangle
\end{align*}
Definiamo induttivamente una catena \(\langle p_{i}:i<\omega\rangle\) di immersioni parziali con \(a_{i} \in \operatorname{dom}(p_{i+1})\) e \(b_{i} \in \operatorname{rng}(p_{i+1})\).

Sia \(p_{0} \in I\) arbitrario. Al passo \(i+1\), usiamo le proprietà 1. e 2. della definizione per ottenere \(p_{i+1}\).

Allora \(p=\bigcup_{i \in \omega}p_{i}\) è l'isomorfismo cercato.
#+END_proof

#+BEGIN_thm
Siano \(M,N\vDash T_{dlo}\) con \(\card{M}=\card{N}=\omega\). Allora \(M\cong N\).
#+END_thm

#+BEGIN_proof
Se \(p:M\to N\) è un'immersione parziale con \(\card{\operatorname{dom}(p)}<\omega\) e \(c \in M\), allora, per gli assiomi di \(T_{dlo}\) è possibile trovare \(d \in N\) tale che \(p\cup\set{(c,d)}\) è ancora un'immersione parziale.

Analogamente, se \(d \in N\) e \(p:M\to N\) è un'immersione parziale con \(\card{\operatorname{dom}(p)}<\omega\), troviamo \(c \in N\) tale che \(p\cup\set{(c,d)}\) è ancora un'immersione parziale.

Dunque \(I=\set{p:M\to N\text{ immersione parziale finita}}\) rende \(M\) e \(N\) parzialmente isomorfe.

Per il lemma dell'andirivieni, \(M\cong N\).
#+END_proof

#+BEGIN_cor
\(T_{dlo}\) è \(\omega\)-categorica.
#+END_cor

#+BEGIN_oss
Ogni teoria \(\omega\)-categorica \(T\) con un modello infinito è completa. Infatti, se \(M,N\vDash T\) e \(\varphi \in L\) è enunciato t.c. \(M\vDash\varphi\), siano \(M',N'\vDash T\) con \(\card{M'}=\card{N'}=\omega\), \(M'\vDash M\), \(N'\vDash N\) (che esistono per LW). Allora \(M'\cong N'\) e, per elementarità, \(N\vDash\varphi\).
#+END_oss

#+BEGIN_cor
\(T_{dlo}\) è completa.
#+END_cor

#+BEGIN_thm
\(T_{rg}\) è coerente.
#+END_thm

#+BEGIN_proof
Si definisce un grafo su \(\omega\) come segue: per \(i<j\), \(R(i,j)\) sse la cifra \(i\)-esima nell'espansione binaria di \(j\) è \(1\).

Dimostrare che \(\langle \omega,R\rangle \vDash T_{rg}\).
#+END_proof

#+BEGIN_thm
Siano \(M,N\vDash T_{rg}\) con \(\card{M}=\card{N}=\omega\). Allora \(M\cong N\).
#+END_thm

#+BEGIN_proof
Siano \(m_{0} \in M\), \(n_{0} \in N\). Allora \(\langle m_{0},n_{0}\rangle\) è un'immersione parziale.

Dunque \(I=\set{p:M\to N\text{ immersione parziale finita}}\neq \emptyset\).

Siano ora \(p \in I\) e \(m \in M\). Considero \(U,V \subseteq \operatorname{rng}(p)\)
\begin{align*}
U&=\set{p(a) \in \operatorname{rng}(p)\mid R(m,a)}\\
V&=\set{p(a) \in \operatorname{rng}(p)\mid \lnotR(m,a)}
\end{align*}
Dunque esiste \(n \in N\) tale che, per ogni \(a \in \operatorname{dom}(p)\)
\begin{equation*}
M\vDash R\big(m,a\big)\quad\iff\quad R\big(n,p(a)\big)
\end{equation*}
...
#+END_proof

#+BEGIN_cor
\(T_{rg}\) è \(\omega\)-categorica e completa.
#+END_cor

Il modello numerabile \(\Gamma\) di \(T_{rg}\) si chiama _grafo di Rado_, o _random graph_.

Ogni grafo finito e ogni grafo numerabile si immerge in \(\Gamma\).

Inoltre \(\Gamma\) è _ultraomogeneo_: ogni isomorfismo tra sottografi finiti di \(\Gamma\) si estende ad un automorfismo di \(\Gamma\).

Anche \(\langle\Q,<\rangle\) è ultraomogeneo. ...

#+BEGIN_definizione
Una mappa \(f:\operatorname{dom}(f) \subseteq M\to N\) si dice _elementare_ se \(\forall \varphi(x) \in \mathcal{L}\), \(a \in \operatorname{dom}(f)^{|x|}\)
\begin{equation*}
M\vDash\varphi(a)\quad\iff\quad N\vDash\varphi\big(f(a)\big).
\end{equation*}
#+END_definizione

#+BEGIN_prop
Una mappa è elementare sse ogni sua restrizione finita lo è.
#+END_prop
#+BEGIN_proof
(\(\Rightarrow\)): ovvio.

(\(\Leftarrow\)): siano \(\varphi(x) \in \mathcal{L}\) e \(a \in M\) tali che
\begin{equation*}
M\vDash\varphi(a)\quad \land \quad N\not\vDash\varphi(f(a))
\end{equation*}
Allora \(f\upharpoonright \set{a}\) è finita e non elementare.
#+END_proof

#+BEGIN_thm
Siano \(M,N\vDash T_{dlo}\) (o \(T_{rg}\)), e sia \(p:M\to N\) un'immersione parziale. Allora \(p\) è elementare.
#+END_thm
#+BEGIN_proof
In virtù della proposizione precedente, basta il caso \(\card{p}<\omega\).

Siano \(M'\preceq M\), \(N'\preceq N\) tali che \(\card{M'}=\card{N'}=\omega\) e
\begin{align*}
\operatorname{dom}(p) &\subseteq M'\\
\operatorname{rng}(p) &\subseteq N'
\end{align*}
Allora per andirivieni fra \(M'\) e \(N'\), \(p\) si estende a \(\pi:M'\cong N'\).

In particolare, \(p\) è elementare.
#+END_proof
#+BEGIN_cor
\(\langle \Q,<\rangle\preceq\langle \R,<\rangle\)
#+END_cor

* Tipi

Tutte le strutture si intendono in un linguaggio \(\mathcal{L}\) fissato.

#+BEGIN_definizione
Un _tipo_ \(p(x)\) è un insieme di \(\mathcal{L}\)-formule le cui variabili libere sono in \(x=\langle x_{i}:i<\lambda\rangle\), con \(\lambda\) cardinale.
#+END_definizione

Notazione: \(p(x) \subseteq \mathcal{L}\)

#+BEGIN_definizione
Un tipo \(p(x)\) è
- _soddifacibile in \(M\)_ se \(\exists a \in M^{|x|}\) tale che
  \begin{equation*}
	M\vDash\varphi(a)\quad\text{ per ogni }\varphi(x) \in p(x);
  \end{equation*}
  scriviamo \(M\vDash p(a)\), oppure \(M,a\vDash p(x)\) e diciamo che \(a\) _realizza_ \(p(x)\) in \(M\);
- _soddisfacibile_ se è soddisfacibile in qualche \(M\);
- _finitamente soddisfacibile in \(M\)_ se ogni \(q(x)\subseteq p(x)\) finito è soddisfacibile in \(M\);
- _finitamente soddisfacibile_ se ogni \(q(x)\subseteq p(x)\) finito è soddisfacibile.
#+END_definizione

Spesso si dice "consistente" invece di "soddisfacibile".

#+BEGIN_esempio
Sia \(M=\langle \N, <\rangle\), sia \(\varphi_{n}(x)\) la formula "ci sono almeno \(n\) elementi \(<x\)", e sia
\begin{equation*}
p(x)=\set{\varphi_{n}(x)\mid n \in \omega}.
\end{equation*}
- \(p(x)\) è finitamente soddisfacibile in \(M\).
- \(p(x)\) non è soddisfacibile in \(M\).
#+END_esempio

#+BEGIN_thm
(Teorema di Compattezza)\hspace{1em} Una teoria \(T\) è coerente se e solo se è coerente ogni sottoinsieme finito di \(T\).
#+END_thm
Un corollario è
#+BEGIN_thm
(compattezza per tipi)\hspace{1em} Se \(p(x)\) è un tipo finitamente soddisfacibile, allora \(p(x)\) è soddisfacibile.
#+END_thm

#+BEGIN_lem
(Lemma del diagramma)\hspace{1em} Sia \(a=\langle a_{i}:i<\lambda\rangle\) una enumerazione della struttura \(M\). Sia \(q(x)\) il _diagramma di \(M\)_:
\begin{equation*}
q(x)=\set{\varphi(x) \in \mathcal{L}\mid M\vDash\varphi(a)},\quad |x|=|a|=\lambda.
\end{equation*}
Allora \(q(x)\) è soddisfacibile in una struttura \(N\) se e solo se esiste \(\beta:M\to N\) immersione elementare.
#+END_lem

#+BEGIN_proof
(\(\Leftarrow\)): \(N\vDash q\big(\beta(a)\big)\).
(\(\Rightarrow\)): Se \(b \in N^{|x|}\) è tale che \(N\vDash q(b)\), allora
\begin{equation*}
\beta:a_{i}\mapsto b_{i},\quad i<\lambda
\end{equation*}
è una immersione elementare. Quindi
\begin{equation*}
M\vDash \varphi(a)\quad\iff\quad \varphi(x) \in q(x)\quad \iff \quad N\vDash \varphi(b) = \varphi\big(\beta(a)\big).\qedhere
\end{equation*}
#+END_proof

Se \(A \subseteq M\), consideriamo i tipi in \(\mathcal{L}(A)\), detti _con parametri in \(A\)_, o _su \(A\)_.

In particolare, se \(A=M\) e \(p(x) \subseteq \mathcal{L}(M)\), esistono:
1. \(a=\langle a_{i}:i<\card{M}\rangle\) enumerazzione
2. \(q(x,z) \subseteq \mathcal{L}\)
tali che \(p(x) = q(x,a)\).

Allora il lemma precedente si può enunciare come segue.
#+BEGIN_lem
Sia \(\operatorname{Th}(M_{M})\) la teoria di \(M\) in \(\mathcal{L}(M)\). Se \(N\vDash\operatorname{Th}(M_{M})\), allora \(M\preceq N\).
#+END_lem
#+NAME: thm:realtipifinsodd
#+BEGIN_thm
Sia \(M\) una struttura e \(p(x) \subseteq \mathcal{L}(M)\) un tipo finitamente soddisfacibile in \(M\). Allora \(p(x)\) è realizzato in qualche \(N\succeq M\).
#+END_thm

#+BEGIN_esempio
Sia \(M=(0,1) \subseteq \Q\) una \(\mathcal{L}_{lo}\)-struttura. Siano
1. \(a_{n}=1-1/n \in M\) per \(n \in \omega\setminus\set{0}\);
2. \(p(x) = \set{a_{n}<x: n \in \omega}\).

Allora \(p(x) \in \mathcal{L}(M)\) è finitamente sodidsfacibile in \(M\), ma non è realizzato. Viceversa
\begin{equation*}
\Q,1\vDash p(x)
\end{equation*}
e sappiamo che \(M\preceq \Q\).
#+END_esempio
#+BEGIN_proof
(del Teorema~\ref{thm:realtipifinsodd})\hspace{1em} Siano:
1. \(a\) una enumerazione di \(M\);
2. \(p(x)=p'(x,a)\) con \(p'(x,z) \subseteq\mathcal{L}\), \(|z|=\card{a}=\card{M}\);
3. \(q(z) = \set{\varphi(z)\mid M\vDash\varphi(a)}\).

Allora \(p'(x,z)\cup q(z)\) è finitamente soddisfacibile, per ipotesi. Per compattezza, esiste una struttura \(N\) e \(c,d\) tali che
\begin{equation*}
N,c,d\vDash p'(x,z)\cup q(z)
\end{equation*}
e in particolare \(N\vDash q(d)\) e dunque esiste \(\beta:M\to N\) immersione elementare. Possiamo assumere \(M\preceq N\).
#+END_proof
Un corollario è questo importante teorema.
#+BEGIN_thm
(Lowenheim-Skolem all'insù)\hspace{1em} Sia \(\card{M}\ge \omega\). Allora per ogni \(\lambda\ge \card{M}+\card{\mathcal{L}}\) esiste \(N\succeq M\) con \(\card{N}=\lambda\).
#+END_thm
#+BEGIN_proof
Sia \(x=\langle x_{i}: i<\lambda\rangle\) una tupla di variabili distinte, e sia
\begin{equation*}
p(x)=\set{x_{i}\neq x_{j}\mid i<j<\lambda}.
\end{equation*}
Allora \(p(x)\) è finitamente soddisfacibile in \(M\), e dunque realizzato in \(N\succeq M\), con \(\card{N}\ge \lambda\).

Per Lowenheim-Skolem all'ingiù, possiamo assumere \(\card{N}=\lambda\).
#+END_proof

* Saturazione

#+BEGIN_definizione
Sia \(\lambda\) un cardinale infinito. La struttura \(M\) si dice \(\lambda\)-satura se realizza ogni tipo \(p(x) \subseteq \mathcal{L}(A)\) (per \(A \subseteq M\)) con
1. \(\card{x}=1\)
2. \(p(x)\) è finitamente soddisfacibile in \(M\);
3. \(\card{A}\le\lambda\).

\(M\) si dice satura se è \(\card{M}\)-satura.
#+END_definizione

#+begin_esempio
Sia \(p(x) = \set{x\neq a\mid  a \in M} \subseteq \mathcal{L}(M)\):
- \(p(x)\) è finitamente soddisfacibile in \(M\);
- \(p(x)\) non è soddisfacibile in \(M\).
#+end_esempio

#+BEGIN_definizione
Se \(A \subseteq M\) e \(b \in M^{|b|}\) allora il _tipo di \(b\) su \(A\)_ è
\begin{equation*}
\operatorname{tp}_{M}(b/A) \coloneqq\set{\varphi(x) \in \mathcal{L}(A): M\vDash \varphi(b)}.
\end{equation*}
#+END_definizione

#+BEGIN_oss
Si ha che
1. \(\operatorname{tp}(b/A)\) è completo: se \(\varphi(x) \in \mathcal{L}(A)\), si ha \(M\vDash\varphi(b)\) o \(M\vDash \lnot\varphi(b)\);
2. se \(A \subseteq M\preceq N\) e \(b \in M^{|b|}\)
   \begin{equation*}
	\operatorname{tp}_{M}(b/A) = \operatorname{tp}_{N}(b/A);
   \end{equation*}
#+END_oss

_Importante_ se \(M\equiv N\), allora \(\emptyset:M\partialto N\) è elementare.

#+BEGIN_prop
Sia \(f:\operatorname{dom}(f) \subseteq M\to N\) elementare. Allora:
1. \(M\equiv N\);
2. Se \(a\) enumera \(\operatorname{dom}(f)\)
   \begin{equation*}
	\operatorname{tp}(a/\emptyset) = \operatorname{tp}\big(f(a)/\emptyset\big)
   \end{equation*}
   e più in generale, se \(b \in \operatorname{dom}(f)^{|b|}\), se \(A \subseteq \operatorname{dom}(f)\cap N\) e \(f\upharpoonright A = \Id_{A}\):
   \begin{equation*}
	\operatorname{tp}(b/A) = \operatorname{tp}\big(f(b)/A\big).
   \end{equation*}
3. Se \(a\) enumera \(\operatorname{dom}(f)\) e \(p(x,a) \subseteq L(A)\) è finitamente soddisfacibile in \(M\), allora \(p\big(x,f(a)\big)\) è finitamente soddisfacibile in \(N\).

   Infatti, se \(\set{\varphi_{1}(x,a),\dots,\varphi_{n}(x,a)} \subseteq p(x,a)\) allora
   \begin{equation*}
	M\vDash \exists x \bigwedge_{i=1}^{n} \varphi_{i}(x,a)
   \end{equation*}
   e per elementarità di \(f\)
   \begin{equation*}
	N\vDash \exists x \bigwedge_{i=1}^{n} \varphi_{i}\big(x,f(a)\big).
   \end{equation*}
#+END_prop

#+BEGIN_thm
Sia \(N\) tale che \(\card{\mathcal{L}}+\omega\le\lambda\le\card{N}\). Sono fatti equivalenti:
1. \(N\) è \(\lambda\)-satura;
2. se \(f:M\partialto N\) è mappa elementare con \(\card{f}\le \lambda\) e \(b \in M\), allora esiste \(\hat{f}\supseteq f\) elementare tale che \(b \in \operatorname{dom}(\hat{f})\) ;
3. se \(A \subseteq N\) è tale che \(\card{A}<\lambda\) e \(p(z) \subseteq \mathcal{L}(A)\) con \(\card{z}\le\lambda\) è finitamente soddisfacibile in \(N\), allora \(p(z)\) è soddisfacibile in \(N\).
#+END_thm
#+begin_proof
(\(1. \Rightarrow 2.\)): Sia \(f\) come in 2., sia \(b \in M\). Sia \(a\) un'enumerazione di \(\operatorname{dom}(f)\), e sia \(p(x,a)=\operatorname{tp}_{M}(b/a)\).

\(p(x,a)\) è soddisfacibile in \(M\), e dunque \(p\big(x,f(a)\big)\) è finitamente soddisfacibil e in \(N\) e \(\card{f(a)}<\lambda\), \(N\) è \(\lambda\)-satura.

Dunque \(p\big(x,f(a)\big)\) è realizzato in \(N\). Sia \(d\) tale che \(N,d\vDash p\big(x,f(a)\big)\). Allora \(\hat{f}=f\cup\set{(b,d)}\) è la mappa cercata.
#+end_proof

#+BEGIN_cor
Se \(M,N\) sono saturi con \(\card{M}=\card{N}\), allora ogni mappa elementare \(f:M\partialto N\) tale che \(\card{f}<\card{M}\) si estende ad un isomorfismo \(\alpha:M\cong N\).

In particolare, se \(M,N\) sono saturi, \(\operatorname{Th}(M)=\operatorname{Th}(N)\) e \(\card{M}=\card{N}\), allora \(M\cong N\).
#+END_cor
#+BEGIN_cor
Se \(M\vDash T_{dlo}\) o \(M\vDash T_{rg}\), allora \(M\) è \(\omega\)-saturo.
#+END_cor

Ricordiamo che un _automorfismo_ di una struttura \(M\) è un isomorfismo \(M\to M\). Gli automorfismi di \(M\) formano un gruppo, scritto \(\operatorname{Aut}(M)\).

Se \(A \subseteq M\), si definisce
\begin{equation*}
\operatorname{Aut}(M/A) \coloneqq\set{\alpha \in \operatorname{Aut}(M) \mid \alpha\upharpoonright=\Id_{A}}.
\end{equation*}
l'insieme degli automorfismi di \(M\) che fissano \(A\).

#+begin_definizione
Sia \(\lambda\) un cardinale infinito. Una struttura \(N\) è
1. _\(\lambda\)-universale_ se per ogni \(M\equiv N\) con \(\card{M}\le \lambda\), esiste \(\beta:M\to N\) immersione elementare, e _universale_ se è \(\card{N}\)-universale;
2. _\(\lambda\)-omogenea_ se ogni mappa elementare \(f:N\partialto N\), con \(\card{f}<\lambda\), si estende ad \(\alpha \in \operatorname{Aut}(N)\), e _omogenea_ se è \(\card{N}\)-omogenea;
3. _ultraomogenea_ se ogni immersione parziale finita si estende ad un automorfismo.
#+end_definizione

#+BEGIN_thm
Sia \(N\) tale che \(\card{N}\ge \card{L}\). Sono equivalenti:
1. \(N\) è satura;
2. \(N\) è universale e omogenea.
#+END_thm

#+BEGIN_definizione
Sia \(a \in N^{|a|}\) e sia \(A \subseteq N\). Allora
1. l'_orbita di \(a\) su \(A\)_ è
   \begin{equation*}
	O_{N}(a/A) \coloneqq \set{\alpha(a): \alpha \in \operatorname{Aut}(N/A)},
   \end{equation*}
   dove per definizione \(alpha(a_{0},\dots,a_{i},\dots) \coloneqq \big(\alpha(a_{0}),\dots,\alpha(a_{i}),\dots\big)\);
2. se \(\varphi \in \mathcal{L}(A)\),
   \begin{equation*}
	\varphi(N) \coloneqq \set{a \in N^{|x|}:N\vDash\varphi(a)}
   \end{equation*}
   è l'insieme _definito_ da \(\varphi(x)\).

Un sottoinsieme di \(N\) è _definibile su \(A\)_ se è definito da qualche \(\varphi(x) \in \mathcal{L}(A)\).

Un sottoinsieme di \(N\) è _tipo-definibile su \(A\)_ se è nella forma
\begin{equation*}
p(N) \coloneqq \set{a \in N^{|x|}\mid N\vDash p(a)}
\end{equation*}
per qualche tipo \(p(x) \subseteq \mathcal{L}(A)\).
#+END_definizione

#+BEGIN_oss
Se \(a,b \in N^{|a|}\) e \(A \subseteq N\), allora
\begin{equation*}
\operatorname{tp}(a/A)=\operatorname{tp}(b/A)
\end{equation*}
se e solo se la mappa
\begin{equation*}
\set{\langle a_{i}, b_{i}\rangle\mid i <\card{a}}\cup\Id_{A}
\end{equation*}
è una mappa elementare \(N\to N\).
#+END_oss

#+BEGIN_thm
Siano \(N\) \(\lambda\)-omogenea, \(A \subseteq N\), \(\card{A}<\lambda\), e sia \(a \in N^{|a|}\), con \(|a|<\lambda\).

Sia \(p(x)=\operatorname{tp}(a/A)\). Allora
\begin{equation*}
O_{N}(a/A) = p(N).
\end{equation*}
#+END_thm
#+BEGIN_proof
(\(\subseteq\)) Se \(b \in O_{N}(a/A)\) allora \(b =\alpha(a)\) per \(\alpha \in \operatorname{Aut}(N/A)\) e se \(\varphi(x,c) \in \mathcal{L}(A)\) con \(c\) parametri,
\begin{align*}
N\vDash\varphi(a,c)\quad &\iff\quad N\vDash\varphi\big(\alpha(a),\alpha(c)\big)\\
&\iff\quad N\vDash\varphi(b,c).
\end{align*}
(\(\supseteq\)) Se \(N\vDash p(b)\) allora \(\operatorname{tp}(b/A)=\operatorname{tp}(a/A)\) e
\begin{equation*}
f=\set{\langle a_{i},b_{i}\rangle: i<\card{a}}\cup\Id_{A}
\end{equation*}
è elementare con \(\card{f}<\lambda\).

Per \(\lambda\)-omogeneità, esiste \(\alpha\supseteq f\), \(\alpha \in \operatorname{Aut}(N)\). In particolare, \(\alpha\upharpoonright A =\Id_{A}\), e dunque
\begin{equation*}
b \in O_{N}(a/A).\qedhere
\end{equation*}
#+END_proof

* Modello mostro

Sia \(T\) una teoria completa senza modelli finiti. Lavoriamo in \(\mathcal{U}\vDash T\) tale che
1. \(\mathcal{U}\) è saturo;
2. \(\card{\mathcal{U}}>\card{M}\) per ogni \(M\vDash T\) con cui ci interessa lavorare.

_Avvertimento_: non ci siamo occupati dell'esistenza di un modello saturo di \(T\).

#+BEGIN_definizione
\(N\) è _debolmente \(\lambda\)-omogeneo_ se per ogni \(f:N\partialto N\) elementare e tale che \(\card{f}<\lambda\), e per ogni \(b \in N\), esiste \(c \in N\) tale che \(f\cup\set{\langle b,c\rangle}\) è elementare.
#+END_definizione

In particolare, se \(N\) è \(\lambda\)-saturo, allora
- \(N\) è debolmente \(\lambda\)-omogeneo;
- \(N\) è \(\lambda\)-universale.

_Terminologia e convenzioni in \(\mathcal{U}\)_.
- "vale \(\varphi(x)\)", o "\(\vDash\varphi(x)\)", se \(\mathcal{U}\vDash \forall x \ \varphi(x)\);
- "\(\varphi(x)\) è consistente" se \(\mathcal{U}\vDash \exists x\ \varphi(x)\);
- un tipo \(p(x)\) è coerente/consistente se esiste \(a \in \mathcal{U}^{|x|}\) tale che \(\mathcal{U}\vDash p(a)\);
- un cardinale \(\lambda\) è _piccolo_ se \(\lambda<\card{\mathcal{U}}\);
- \(\card{\mathcal{U}}=\kappa\);
- un _modello_ è \(M\preceq\mathcal{U}\), con \(\card{M}\) piccola;
- \(A,B,C\) sono sottoinsiemi piccoli (ovvero di cardinalità piccola) di \(\mathcal{U}\);
- \(\operatorname{tp}(a/A) \coloneqq \operatorname{tp}_{\mathcal{U}}(a/A)\);
- \(O(a/A) \coloneqq O_{\mathcal{U}}(a/A)\).

_Altre convensioni_
- se non altrimenti specificato, le tuple hanno lunghezza piccola;
- gli insiemi definibili hanno la forma \(\varphi(\mathcal{U})\) per \(\varphi \in \mathcal{L}(\mathcal{U})\);
- i tipi hanno parametri in insiemi piccoli
- gli insiemi tipo-definibili hanno la formula \(p(\mathcal{U})\) per qualche tipo \(p(x) \subseteq \mathcal{L}(A)\), \(A\) piccolo.

Se \(p(x),q(x)\) sono tipi, scriviamo
\begin{align*}
p(x)\implies q(x)\quad&\text{per}\quad p(\mathcal{U}) \subseteq q(\mathcal{U});\\
p(x)\implies \lnot q(x)\quad&\text{per}\quad p(\mathcal{U}) \cap q(\mathcal{U})=\emptyset;
\end{align*}

#+BEGIN_prop
Se \(p(x) \subseteq \mathcal{L}(A)\), \(q(x) \subseteq \mathcal{L}(B)\) sono tipi coerenti e tali che \(p(x)\implies\lnot q(x)\), allora esistono \(\varphi(x)\) e \(\psi(x)\) congiunzione di formule (risp. di \(p(x)\) e \(q(x)\)) tali che
\begin{equation*}
\vDash \varphi(x)\implies\lnot\psi(x)
\end{equation*}
#+END_prop

Infatti, se \(p(\mathcal{U})\cap q(\mathcal{U}) = \emptyset\), allora
\begin{equation*}
p(x)\cup q(x)
\end{equation*}
non è soddisfacibile in \(\mathcal{U}\), e dunque (siccome \(\mathcal{U}\) è saturo), non è finitamente soddisfacibile.

#+BEGIN_prop
Se \(\alpha \in \operatorname{Aut}(\mathcal{U})\) e \(\varphi(\mathcal{U},b)\) è un insieme definibile, allora
\begin{equation*}
\alpha\big[\varphi(\mathcal{U},b)\big] = \varphi\big(\mathcal{U},\alpha(b)\big).
\end{equation*}
Analogamente, se \(p(x,z) \subseteq \mathcal{L}\) e \(b \in \mathcal{U}^{|z|}\)
\begin{equation*}
\alpha\big[p(\mathcal{U},b)\big]=p\big(\mathcal{U},\alpha(b)\big).
\end{equation*}
#+END_prop

#+BEGIN_definizione
Un insieme \(D \subseteq \mathcal{U}^{\lambda}\) (per \(\lambda<\kappa\)) è _invariante_ su \(A \subseteq\mathcal{U}\) se per ogni \(\alpha \in \operatorname{Aut}(\mathcal{U}/A)\),
\begin{equation*}
\alpha[D]=D.
\end{equation*}
o, equivalentemente,
\begin{equation*}
\forall a \in D\quad O(a/A) \subseteq D.
\end{equation*}
#+END_definizione
#+BEGIN_oss
Se \(b\vDash \operatorname{tp}(a/A)\), allora, per omogeneità esiste \(\alpha \in \operatorname{Aut}(\mathcal{U}/A)\) tale che \(\alpha(a)=b\), dunque \(b \in O(a/A)\).

Quindi \(D\) è invariante se e solo se
\begin{equation*}
\forall  a \in D,\ \forall  b \in \mathcal{U},\quad \operatorname{tp}(a/A) =\operatorname{tp}(b/A)\implies b \in D.
\end{equation*}
#+END_oss
#+NAME: thm:oijsoidkjnjjjjjd
#+BEGIN_thm
Sia \(A \subseteq \mathcal{U}\). Per ogni \(\varphi(x) \in \mathcal{L}(\mathcal{U})\), sono equivalenti:
1. esiste \(\psi(x) \in \mathcal{L}(A)\) tale che
   \begin{equation*}
	\vDash \forall x\ \big[\psi(x)\iff\varphi(x)\big];
   \end{equation*}
2. \(\varphi(\mathcal{U})\) è invariante su \(A\).
#+END_thm

Notiamo che la condizione 1. dice che \(\varphi(\mathcal{U})\) è definibile su \(A\).

#+BEGIN_oss
Sottoinsiemi finiti e cofiniti di \(\mathcal{U}\) sono sempre definibili.
#+END_oss
#+BEGIN_proof
(del Teorema\nbsp{}\ref{thm:oijsoidkjnjjjjjd})\hspace{0.7em} (\(2.\Rightarrow 1.\)): Siano \(\varphi(x,z) \in \mathcal{L}\) e \(b \in \mathcal{U}^{|z|}\) tali che \(\varphi(\mathcal{U},b)\) è invariante su \(A\).

Sia \(c\vDash \operatorname{tp}(b/A)\). Per omogeneità, \(c=\alpha(b)\) per qualche \(\alpha \in \operatorname{Aut}(\mathcal{U}/A)\). Allora
\begin{equation*}
\alpha\big[\varphi(\mathcal{U},b)\big]=\varphi(\mathcal{U},c)
\end{equation*}
me ma per invarianza \(\alpha\big[\varphi(\mathcal{U},b)\big]=\varphi(\mathcal{U},b)\), e pertanto
\begin{equation*}
\varphi(\mathcal{U},c)=\varphi(\mathcal{U},b).
\end{equation*}

Allora, se \(q(z)\coloneqq\operatorname{tp}(b/A)\)
\begin{equation*}
q(z)\implies \forall x\ \big[\varphi(x,b)\iff\varphi(x,z)\big].
\end{equation*}
Per saturazione/compattezza, esiste \(\chi(z) \in q(z)\) tale che
\begin{equation*}
\vDash \chi(z)\implies \forall x\ \big[\varphi(x,b)\iff\varphi(x,z)\big].
\end{equation*}
Allora \(\varphi(\mathcal{U},b)\) è definito da
\begin{equation*}
\exists z\ [\chi(z) \land \psi(x,z)] \in \mathcal{L}(A).\qedhere
\end{equation*}
#+END_proof

** Eliminazione dei quantificatori

#+BEGIN_prop
Sia \(\varphi(x) \in \mathcal{L}\). Sono fatti equivalenti:
1. esiste \(\psi(x)\) senza quantificatori tale che
   \begin{equation*}
	\vDash \forall x\ \big[\varphi(x)\iff\psi(x)\big].
   \end{equation*}
2. per ogni immersione parziale \(p:\mathcal{U}\partialto\mathcal{U}\), \(a \in \operatorname{dom}(p)^{|x|}\)
   \begin{equation*}
	\vDash \varphi(a)\iff\varphi\big(p(a)\big).
   \end{equation*}
#+END_prop
#+BEGIN_proof
(\(1.\Rightarrow 2.\)): abbastanza ovvia.

(\(2.\Rightarrow 1.\)): Per \(a \in \mathcal{U}^{|x|}\), sia
\begin{equation*}
\operatorname{qftp}(a) \coloneqq \set{\chi(x) \in \operatorname{tp}(a/\emptyset)\mid \chi(x)\text{ senza quantificatori}}
\end{equation*}
e sia
\begin{equation*}
\mathcal{F}\coloneqq\set{q(x)\mid q(x)=\operatorname{qftp}(a)\text{ per }a \in \varphi(\mathcal{U})}.
\end{equation*}
Vogliamo dimostrare che
\begin{equation*}
\varphi(\mathcal{U}) = \bigcup_{q \in \mathcal{F}}q(\mathcal{U}).
\end{equation*}
Per \(\subseteq\) è ovvio per definizione di \(\mathcal{F}\).

Per \(\supseteq\), sia \(q(x) \in \mathcal{F}\), \(q(x)=\operatorname{qftp}(a)\) e sia \(b\vDash q(x)\).

Allora \(a_{i}\mapsto b_{i}\) è immersione parziale, dunque per ipotesi \(\vDash \varphi(b)\).

Dunque \(q(\mathcal{U}) \subseteq \varphi(\mathcal{U})\), e dunque \(\varphi(\mathcal{U}) \supseteq \bigcup_{q \in \mathcal{F}}q(\mathcal{U})\).

In particolare \(q(x)\implies \varphi(x)\) per ogni \(q(x) \in \mathcal{F}\). Allora esiste \(\psi_{q}(x) \in q(x)\) tale che
\begin{equation*}
\vDash \psi_{q}(x)\implies\varphi(x)
\end{equation*}
(per compattezza/saturazione).

FINIRE DIMOSTRAZIONE
#+END_proof

#+BEGIN_definizione
Una teoria \(T\) ha l'_eliminazione dei quantificatori_ (q.e.) se per ogni \(\varphi(x) \in \mathcal{L}\) esiste \(\psi(x)\) senza quantificatori tale che
\begin{equation*}
T\vDash \forall x\ \big[\varphi(x)\iff\psi(x)\big].
\end{equation*}
#+END_definizione

Se \(T\) è completa e ha q.e., il tipo di \(a \in \mathcal{U}^{|a|}\) è determinato di \(\operatorname{qftp}(a)\).

#+BEGIN_thm
Sia \(T\) completa senza modelli finiti. Sono fatti equivalenti:
1. \(T\) ha q.e.
2. ogni immersione parziale \(p:\mathcal{U}\partialto \mathcal{U}\) è elementare;
3. per ogni \(p:\mathcal{U}\partialto\mathcal{U}\) con \(\card{p}<\card{\mathcal{U}}\) e \(b \in \mathcal{U}\), esiste \(\hat{p}\supseteq p\) immersione parziale con \(\card{\hat{p}}<\card{\mathcal{U}}\) e \(b \in \operatorname{dom}(\hat{p})\);
4. per ogni \(p:\mathcal{U}\partialto\mathcal{U}\) con \(\card{p}<\omega\) e \(b \in \mathcal{U}\), esiste \(\hat{p}\supseteq p\) immersione parziale con \(\card{\hat{p}}<\omega\) e \(b \in \operatorname{dom}(\hat{p})\).
#+END_thm
#+BEGIN_proof
(\(1.\Rightarrow 2.\)): Ogni \(\varphi(x) \in \mathcal{L}\) è equivalente a \(\psi(x)\) senza quantificatori, e \(p\) preserva \(\psi(x)\).

(\(2.\Rightarrow 1.\)): \(p\) è immersione parziale, dunque \(p\) elementare, e dunque \(p\) preserva ogni \(\varphi(x) \in \mathcal{L}\).

Dal teorema precedente, \(\varphi(x)\) è equivalente a \(\psi(x)\) senza quantificatori, e questo vale per ogni \(\varphi(x) \in \mathcal{L}\).

(\(2.\Rightarrow 3.\)): Sia \(p\) parziale e \(\card{p}<\card{\mathcal{U}}\). Allora \(p\) è elementare e per omogeneità di \(\mathcal{U}\), \(p \subseteq \alpha \in \operatorname{Aut}(\mathcal{U})\). Pertanto è sufficiente porre \(\hat{p}\coloneqq p\cup\set{\langle b,\alpha(b)\rangle}\).

(\(3.\Rightarrow 2.\)) (traccia): Se \(p_{0}\subseteq p\), \(\card{p_{0}}<\omega\), estendiamo \(p_{0}\) ad \(\alpha \in \operatorname{Aut}(\mathcal{U})\) per back-and-forth. Allora \(p_{0}\) è elementare.
#+END_proof

** Insiemi definibili e algebrici

#+BEGIN_definizione
1. \(a \in \mathcal{U}\) è _definibile su \(A \subseteq\mathcal{U}\)_ se \(\set{a}\) è definibile su \(A\) (ovvero \(\varphi(\mathcal{U})=\set{a}\) per qualche \(\varphi(x) \in \mathcal{L}(A)\)).
2. \(a \in \mathcal{U}\) è _algebrico su \(A \subseteq \mathcal{U}\)_ se esiste \(\varphi(x) \in \mathcal{L}(A)\) tale che \(a \in \varphi(\mathcal{U})\) e \(\card{\varphi(\mathcal{U})}<\omega\). (Una tale \(\varphi(x)\) si dice _algebrica_).
3. La _chiusura definibile_ di \(A \subseteq \mathcal{U}\) è
   \begin{equation*}
	\operatorname{dcl}(A) = \set{a \in \mathcal{U}\mid a\text{ è definibile su }A}.
   \end{equation*}
4. La _chiusura algebrica_ di \(A \subseteq \mathcal{U}\) è
   \begin{equation*}
	\operatorname{acl}(A) = \set{a \in \mathcal{U}\mid a\text{ è algebrico su }A}.
   \end{equation*}
#+END_definizione

Ovviamente \(\operatorname{dcl}(A) \subseteq \operatorname{acl}(A)\)

#+begin_esempio
Sia \(T_{do} =\operatorname{Th}(\Z,<)\). Si dimostra che \(T_{\text{do}}\) è assiomatizzata da
\begin{align*}
\forall x\ &\lnot(x<x)\\
\forall x,y,z\ &\big[(x<y \land y<z)\implies x<z\big]\\
\forall x,y\ &\big[\big]
\end{align*}
FINIRE GLI ASSIOMI.

\(T_{\text{do}}\) è completa, ma non è \(\omega\)-categorica. (ad esempio \(2.\Z\vDash T_{\text{do}}\)).

Considerando invece \(\Q.\Z\vDash T_{\text{do}}\) (ovvero \(\Q\) copie di \(\Z\)): questo è un modello saturo (ovvero \(\omega\)-saturo e numerabile).

Un modello mostro \(\mathcal{U}\vDash T_{\text{do}}\) ha la forma \(\mathcal{V}.\Z\), dove \(\mathcal{V}\vDash T_{\text{dlo}}\) è un modello mostro.
#+end_esempio

#+BEGIN_oss
Sia \(p(x) \subseteq \mathcal{L}(A)\), con \(\card{x}<\omega\).
\begin{equation*}
\card{p(\mathcal{U})}\ge\omega\quad\iff\quad \card{p(\mathcal{U})}=\card{\mathcal{U}}.
\end{equation*}
In particolare, se \(\varphi(x)\) non è algebrica, allora \(\card{\varphi(\mathcal{U})}=\card{\mathcal{U}}\).

Infatti, sia
\begin{equation*}
q(x)=p(x) \cup\set{x\neq d\mid d \in p(\mathcal{U})}
\end{equation*}
tipo con parametri in \(A \cup p(\mathcal{U})\). Allora \(q(x)\) è finitamente soddisfacibile.

Supponiamo \(\omega\ge \card{p(\mathcal{U})} < \card{\mathcal{U}}\). Allora per saturazione \(\mathcal{U}\vDash q(b)\) per qualche \(b \in \mathcal{U}\).

Allora \(\mathcal{U}\vDash p(b)\), ma \(b\neq d\) per ogni \(d \in p(\mathcal{U})\). Assurdo.

L'unica possibilità è che \(\card{p}(\mathcal{U})=\card{\mathcal{U}}\).
#+END_oss
#+BEGIN_prop
Per \(a \in \mathcal{U}\) e \(A \subseteq \mathcal{U}\) sono fatti equivalenti:
1. \(a \in \operatorname{dlc}(A)\);
2. \(O(a/A) =\set{a}\).
#+END_prop
#+BEGIN_proof
(\(1.\Rightarrow 2.\)): Sia \(\set{a}\) definito da \(\varphi(x) \in \mathcal{L}(A)\), ossia \(\varphi(\mathcal{U})=\set{a}\).

Ma \(\varphi(\mathcal{U})\) è invariante su \(A\), e quindi \(O(a/A) \subseteq \varphi(U)=\set{a}\).

(\(2.\Rightarrow 1.\)): \(O(a/A)=\set{a}\) è definibile (da \(x=a\)) ed è invariante su \(A\) (perché è un'orbita).

Ma allora \(\set{a}\) è definibile da \(\varphi(x) \in \mathcal{L}(A)\), e quindi
\begin{equation*}
a \in \operatorname{dlc}(A)\qedhere
\end{equation*}
#+END_proof

#+BEGIN_thm
Se \(a \in \mathcal{U}\) e \(A \subseteq \mathcal{U}\), sono fatti equivalenti:
1. \(a \in \operatorname{acl}(A)\);
2. \(\card{O(a/A)}<\omega\);
3. \(a \in M\) per ogni mdoello \(M\) tale che \(A \subseteq M\).
#+END_thm
#+BEGIN_proof
(\(1.\Leftrightarrow 2.\)): è simile al caso definibile su \(A\).

(\(1.\Rightarrow 3.\)): Se \(a \in \operatorname{acl}(A)\) allora esiste \(\varphi(x) \in \mathcal{L}(A)\) tale che
\begin{equation*}
\vDash \varphi(a) \land \exists^{=n} x\ \varphi(x).
\end{equation*}
Allora se \(M \preceq \mathcal{U}\) e \(A \subseteq M\), si ha
\begin{equation*}
M\vDash \exists^{=n} x\ \varphi(x)
\end{equation*}
Poiché ogni testimone di \(\varphi(x)\) in \(M\) è un testimone in \(\mathcal{U}\), \(\varphi(\mathcal{U}) \subseteq M\); in particolare, \(a \in M\).

(\(3.\Rightarrow 1.\)): se \(a\notin \operatorname{acl}(A)\), allora \(p(x) = \operatorname{tp}(a/A)\) è tale che \(\card{p(\mathcal{U})}\ge \omega\), e dunque
\begin{equation*}
\card{p(\mathcal{U})}=\card{\mathcal{U}}
\end{equation*}
e \(p(\mathcal{U})\setminus M\neq \emptyset\) per ogni modello \(M\supseteq A\).

Se \(b \in p(\mathcal{U})\setminus M\), spostiamo
- \(b\) in \(a\) con \(\alpha \in \operatorname{Aut}(\mathcal{U}/A)\);
- \(M\) in \(\alpha[M] \preceq \mathcal{U}\)
e \(a=\alpha(b)\notin \alpha[M]\).
#+END_proof
#+BEGIN_cor
Vale
\begin{equation*}
\operatorname{acl}(A)=\bigcap \set{M\preceq \mathcal{U}\mid A \subseteq M}.
\end{equation*}
#+END_cor
#+BEGIN_prop
Alcune proprietà di \(\operatorname{acl}(A)\):
1. carattere finito: se \(a \in \operatorname{acl}(A)\) allora esiste \(A_{0} \subseteq A\) finito tale che \(a \in \operatorname{acl}(A_{0})\)
2. \(A \subseteq \operatorname{acl}(A)\);
3. \(A \subseteq B\implies \operatorname{acl}(A) \subseteq \operatorname{acl}(B)\);
4. \(\operatorname{acl}\big(\operatorname{acl}(A)\big)=\operatorname{acl}(A)\).
#+END_prop

#+BEGIN_prop
Se \(\beta \in \operatorname{Aut}(\mathcal{U})\) e \(A \subseteq \mathcal{U}\), allora
\begin{equation*}
\beta\big[\operatorname{acl}(A)\big] = \operatorname{acl}\big(\beta[A]\big).
\end{equation*}
#+END_prop
#+BEGIN_proof
Sia \(a \in \operatorname{acl}(A)\) algebrico per la formula \(\varphi(x,b)\), \(b \in \mathcal{U}^{|b|}\).

Allora \(\card{\varphi(\mathcal{U},b)}<\omega\), e valgono
1. \(\vDash\varphi\big(\beta(a),\beta(b)\big)\);
2. \(\card{\varphi(\mathcal{U},\beta(b))}<\omega\)
poiché \(\beta\) è automorfismo.

Segue che \(\beta(a)\) è algebrico su \(\beta(b)\), e dunque
\begin{equation*}
\beta\big[\operatorname{acl}(A)\big] \subseteq \operatorname{acl}\big(\beta[A]\big).\qedhere
\end{equation*}
#+END_proof


* Teorie Fortemente Minimali

Ricordiamo che in ogni struttura \(M\), gli insiemi finiti e cofiniti sono sempre definibili.

#+BEGIN_definizione
Una struttura \(M\) è _minimale_ se tutti i suoi sottoinsiemi definibili sono finiti o cofiniti.
- \(M\) è _fortemente minimale_ se è minimale e ogni sua estensione elementare è minimale.
- Una teoria \(T\) coerente e senza modelli finiti è _fortemente minimale_ se per ogni \(\varphi(x,\overline{z}) \in \mathcal{L}\) esiste \(n \in \omega\) tale che
  \begin{equation*}
	T\vDash \forall \overline{z}\ \big[\exists^{\le n}x\ \varphi(x,\overline{x}) \lor\exists^{\le n}x\ \lnot\varphi(x,\overline{x})\big]
  \end{equation*}
#+END_definizione

Sia ora \(T\) una teoria completa con modello mostro \(\mathcal{U}\).
#+BEGIN_definizione
Sia \(a \in \mathcal{U}\), \(B \subseteq \mathcal{U}\). Allora \(a\) è _indipendente da \(B\)_ se \(a\notin \operatorname{acl}(B)\).

\(B\) è un _insieme indipendente_ se per ogni \(b \in B\), \(b\) è indipendente da \(B\setminus\set{b}\).
#+END_definizione


#+BEGIN_prop
\(\operatorname{Th}(M)\) è fortemente minimale sse \(M\) è fortemente minimale.
#+END_prop
#+begin_esempio
Sia \(L=\set{E}\), con \(E\) relazione binaria. Sia \(M\) numerabile e \(E\) interpretata come relazione di equivalenza, tale che per ogni \(n \in \omega\setminus\set{0}\), \(M\) contiene esattamente una classe di equivalenza di cardinalità \(n\), e nessuna classe di cardinalità \(\omega\).

Allora \(M\) è minimale (e inoltre \(\operatorname{Th}(M)\) ha q.e.) e ammette \(N\succeq M\) dove \(E\) ha una classe di equivalenza infinita (e _non_ cofinita).
#+end_esempio

---

Lavoriamo in \(T\) completa, fortemente minimale, con modello mostro \(\mathcal{U}\).

#+begin_esempio
Sia \(\K\) un campo, e sia \(\mathcal{L}_{\K}=\set{+,-,0,\set{\lambda}_{\lambda \in \K}}\).

Si assiomatizza un campo vettoriale \(V\) su \(\K\), dove tutto è interpretato nel modo usuale (i \(\lambda\) sono funzioni unarie che rappresentano il prodotto per scalari): questo dà luogo a \(T_{\text{VS}\K}\).

È possibile vedere che \(T_{\text{VS}\K}\):
- è completa;
- ha q.e.;
e pertanto:
- i termini sono combinazioni lineari \(\lambda_{1}\, x_{1}+\dots+\lambda_{n}\,x_{n}\);
- le formule atomiche sono uguaglianze tra combinazioni lineari.

Per q.e., \(T_{\text{VS}\K}\) è fortemente minimale.
#+end_esempio
#+begin_esempio
Sia \(\mathcal{L}_{\text{rng}} = \set{+,\cdot,-,0,1}\). Allora \({\mathrm{ACF}}\) è la \(\mathcal{L}_{\text{rng}}\)-teoria che include:
- gli assiomi di gruppo abeliano;
- gli assiomi di monoide commutativo;
- gli assiomi di campo
- assiomi per la chiusura algebrica.

Sia \(\chi_{p}\equiv [1+1+\dots+1=0]\), dove \(1\) è ripetuto \(p\) volte.
- per \(p\) primo, sia \(\mathrm{ACF}_{p}\coloneqq\mathrm{ACF}\cup\set{\chi_{p}}\);
- \(\mathrm{ACF}_{0} \coloneqq \mathrm{ACF}\cup\set{\lnot\chi_{n}\mid n \in \omega}\).

È possibile mostrare che \(\mathrm{ACF}_{p}\) e \(\mathrm{ACF}_{0}\) sono complete e hanno q.e.

Allora:
- le formule atomiche con parametri sono equazioni polinomiali;
- una formula atomica con una variabile e parametri in \(A\) è equivalente a \(p(x)=0\), dove \(p(x)\) è un polinomio nel sottocampo generato da \(A\).
Quindi:
- le formule atomiche con parametri e una solo variabile libera definiscono insiemi finiti;
- le formule quantifier-free con una variabile e parametri definiscono insiemi finiti o cofiniti.

Per q.e., \(\mathrm{ACF}_{p}\) e \(\mathrm{ACF}_{0}\) sono fortemente minimali.
#+end_esempio
FINIRE CON LE SLIDES

#+BEGIN_lem
(Lemma dello scambio). Siano \(B \subseteq \mathcal{U}\), \(a,b \in \mathcal{U}\setminus\operatorname{acl}(B)\). Allora
\begin{equation*}
b \in \operatorname{acl}(aB)\quad\iff\quad a \in \operatorname{acl}(bB)
\end{equation*}
dove con \(aB\coloneqq B\cup\set{a}\).
#+END_lem
#+BEGIN_proof
Per assurdo, sia \(a \in \operatorname{acl}(bB)\) e \(b \notin \operatorname{acl}(aB)\).

Sia \(\varphi(x,y) \in \mathcal{L}(B)\) tale che
\begin{equation*}
\vDash\varphi(a,b) \land \exists^{\le n} x\ \varphi(x,b)
\end{equation*}
per qualche \(n \in \omega\setminus\set{0}\).

Consideriamo ora
\begin{equation*}
\psi(a,y):\quad \varphi(a,y) \land \exists^{\le n} x\ \varphi(x,y)
\end{equation*}
con \(\psi(a,y) \in \mathcal{L}(aB)\).

Siccome \(b\notin \operatorname{acl}(aB)\), allora \(\card{\psi(a,\mathcal{U})}\ge \omega\), e dunque
\begin{equation*}
\card{\psi(a,\mathcal{U})}=\card{\mathcal{U}}.
\end{equation*}

Inoltre, per forte minimalità, \(\card{\lnot\psi(a,\mathcal{U})}<\omega\).

Sia \(M\) un modello, \(B \subseteq M\): allora \(M\cap \psi(a,\mathcal{U})\neq \emptyset\): sia quindi \(c \in M\cap \psi(a,\mathcal{U})\). Allora
\begin{equation*}
\vDash \psi(a,c) \land \exists^{\le n} x\ \psi(x,c)
\end{equation*}
ossia \(a \in \operatorname{acl}(cB)\).

Dunque \(M \supseteq B\) implica \(a \in M\). Per la caratterizzazione, \(a \in \operatorname{acl}(B)\). Assurdo.
#+END_proof
#+BEGIN_definizione
Se \(B \subseteq C \subseteq \mathcal{U}\), \(B\) è una _base di \(C\)_ se
1. \(B\) è indipendente;
2. \(C \subseteq \operatorname{acl}(B)\) (o, equivalentemente, se \(\operatorname{acl}(B)=\operatorname{acl}(C)\)).
#+END_definizione
#+BEGIN_prop
Se \(B\) è un insieme indipendente e \(a \notin \operatorname{acl}(B)\), allora
\begin{equation*}
B\cup\set{a}
\end{equation*}
è ancora un insieme indipendente.
#+END_prop
#+BEGIN_cor
Se \(B \subseteq C \subseteq \mathcal{U}\), sono fatti equivalenti:
1. \(B\) è una base di \(C\);
2. \(B\) è un sottoinsieme indipendente massimale di \(C\).
#+END_cor

#+BEGIN_thm
(basi di sottoinsiemi di \(\mathcal{U}\)). Sia \(C \subseteq \mathcal{U}\). Allora
1. se \(B \subseteq C\) è indipendente, allora \(B\) si può estendere ad una base di \(C\);
2. se \(A\) e \(B\) sono basi di \(C\), allora \(\card{A}=\card{B}\).
#+END_thm
#+BEGIN_definizione
Sia \(C \subseteq \mathcal{U}\) algebricamente chiuso (ossia \(C=\operatorname{acl}(C)\)) e sia \(A\) una base di \(C\).

Allora \(\operatorname{dim}(C)\coloneqq\card{A}\) è la _dimensione di \(C\)_
#+END_definizione

#+BEGIN_definizione
Se \(a\notin\operatorname{acl}(A)\), \(a\) si dice _trascendente_ su \(A\).
#+END_definizione
In una struttura fortemente minimale, tutti gli elementi trascendenti hanno lo stesso tipo su \(A\).
#+BEGIN_thm
Sia \(f:\mathcal{U}\partialto\mathcal{U}\) una mappa elementare, e siano
\begin{equation*}
b\notin\operatorname{acl}\big(\operatorname{dom}(f)\big);\quad c\notin \operatorname{acl}\big(\operatorname{rng}(f)\big).
\end{equation*}
Allora \(f\cup\set{\langle b,c\rangle}\) è elementare.
#+END_thm
#+BEGIN_proof
Sia \(a\) una enumerazione di \(\operatorname{dom}(f)\) e sia \(\varphi(x,a) \in \mathcal{L}(a)\) (con \(\card{x}=1\)).

Mostriamo \(\vDash \varphi(b,a)\iff\varphi\big(c,f(a)\big)\).
- _Caso 1_: \(\card{\varphi(\mathcal{U},a)}<\omega\). Allora \(\card{\varphi\big(\mathcal{U},f(a)\big)}<\omega\).

  Poiché \(b\notin\operatorname{acl}(A)\) e \(c\notin\operatorname{acl}\big(f(a)\big)\),
  \begin{equation*}
	\vDash\lnot\varphi(b,a) \land \lnot\varphi\big(c,f(a)\big).
  \end{equation*}
- _Caso 2_: FINIRE DALLE SLIDE\qedhere
#+END_proof
#+BEGIN_cor
Ogni biiezione fra sottoinsiemi indipendenti di \(\mathcal{U}\) è elementare.
#+END_cor

Ricordiamo: in qualsiasi teoria \(T\), se \(M\vDash T\) e \(A \subseteq M\), allora \(\operatorname{acl}(A) \subseteq M\). In particolare, ciascun modello è algebricamente chiuso.

Se \(T\) è fortemente minimale, questo implica che ogni modello ha una dimensione.

#+BEGIN_thm
Siano \(M, N \preceq \mathcal{U}\) tali che \(\dim(M)=\dim(N)\). Allora \(M\cong N\).
#+END_thm

COMPLETARE CON LA DIMOSTRAZIONE

Se \(T\) è fortemente minimale e \(\lambda>\card{\mathcal{L}}\), allora \(T\) è \(\lambda\)-categorica.

Infatti: per \(A \subseteq \mathcal{U}\), si ha \(\card{\operatorname{acl}(A)}\le\card{\mathcal{L}(A)}+\omega\) poiché
- ci sono al più \(\card{\mathcal{L}(A)}+\omega\) formule
- ogni \(\varphi(x) \in \mathcal{L}(A)\) ha al più finite soluzioni.

Se \(\card{M}=\lambda>\card{\mathcal{L}}\), allora una base deve avere cardinalità \(\lambda\). Ma ogni due modelli di dimensione \(\lambda\) sono isomorfi.

Morale: i modelli di una teoria fortemente minimale sono determinati a meno di isomorfismi dalla loro dimensione, dunque dalla loro cardinalità se la cardinalità è strettamente maggiore della cardinalità del linguaggio.

#+BEGIN_thm
Sia \(N\) un modello, \(\card{N}\ge \card{\mathcal{L}}\). Sono fatti equivalenti:
1. \(N\) è saturo;
2. \(\dim(N)=\card{N}\).
#+END_thm

Vedi questo sito web: https://www.forkinganddividing.com/.
